/*
====================================================================
⚖️ MAGNITUDE ANALYSIS
====================================================================
Purpose:
    Breaks down the big KPI numbers by different dimensions — 
    answering "how big is this number, split by category?"

What This Script Does:
    - Total customers by country
    - Total customers by gender
    - Total products by category
    - Average cost of products in each category
    - Total revenue generated by each product category
    - Total revenue generated by each individual customer
    - Distribution of quantity sold across countries

Concepts Used:
    - GROUP BY    -> splits data by a dimension (country, gender, 
                     category, customer)
    - LEFT JOIN   -> connects fact table to dimension tables to 
                     bring in descriptive attributes
    - Aggregate functions: SUM(), COUNT(), AVG()

Key Takeaway:
    Raw totals only tell half the story — magnitude analysis 
    reveals where the numbers are coming from, e.g., which 
    countries have the most customers, or which category drives 
    the most revenue.
====================================================================
*/

--find total customers by countries
select country,count(customer_key) as total_customers
from gold.dim_customers
group by country
order by total_customers desc;

--find total customers by gender
select gender,count(customer_id) as total_customers 
from gold.dim_customers 
group by gender 
order by total_customers desc;

--find total products by category
select category , count(product_number) as total_products 
from gold.dim_products 
group by category 
order by total_products desc;

--what is the average costs in each category?
select category,avg(cost) average_cost 
from gold.dim_products 
group by category 
order by average_cost desc;

--what is the total revenue generated by each  category
select p.category,sum(f.sales_amount) as total_revenue
from gold.dim_products as p left join gold.fact_sales as f
on p.product_key = f.product_key 
group by p.category
order by total_revenue desc;

--find total revenue is generated by each customer
select distinct c.customer_key,c.first_name,c.last_name,sum(f.sales_amount  ) as total_revenue
from gold.dim_customers as c left join gold.fact_sales as f
on c.customer_key = f.customer_key
group by c.customer_key,c.first_name,c.last_name
order by total_revenue desc;

--what is the distribution of sold items across countries
select distinct c.country,sum(f.quantity) as total_sold_items
from gold.dim_customers as c left join gold.fact_sales as f
on c.customer_key = f.customer_key
group by c.country
order by total_sold_items desc;
