/*
====================================================================
🥧 PART-TO-WHOLE ANALYSIS
====================================================================
Purpose:
    Answers "how much does each category contribute to the total?" 
    — shifting focus from absolute numbers to relative contribution.

What This Script Does:
    - Calculates total sales generated by each product category
    - Calculates the overall total sales across all categories
    - Calculates what percentage of the overall total each 
      category contributes
    - Formats the result as a readable percentage string (e.g., 
      "23.45%")

Concepts Used:
    - CTE (category_sales)         -> pre-aggregate sales by 
                                       category
    - SUM() OVER ()                -> calculates the grand total 
                                       across all rows (window 
                                       function without partition)
    - CAST() + ROUND()             -> ensures accurate percentage 
                                       math and clean rounding
    - CONCAT()                     -> combines the number and '%' 
                                       symbol into one readable value

Key Takeaway:
    Part-to-whole analysis reveals which categories truly drive 
    the business — a category with high sales might still be a 
    small slice of the overall pie, and this script makes that 
    immediately visible.
====================================================================
*/

--which categories contribute the most to overall sales 
with category_sales as (select 
p.category,
sum(f.sales_amount) as total_sales
from gold.dim_products p 
left join
gold.fact_sales f
on p.product_key = f.product_key
where p.category is not null and f.sales_amount is not null
group by p.category 
)
select 
category,
total_sales,
sum(total_sales) over() as overall_sales,
concat(round((cast(total_sales as float)/sum(total_sales) over())*100,2),'%') as percentage_of_total 
from category_sales
order by total_sales desc;
